import React, { useState } from 'react';
import { TargetEvent, SubmissionBundle } from '../types/radar';
import { Package, Download, Copy, Check, Video, FileText, Sparkles, ExternalLink } from 'lucide-react';

interface SubmissionPackagerViewProps {
  activeTarget: TargetEvent;
  onGenerateBundle: () => void;
  isPackaging: boolean;
}

export const SubmissionPackagerView: React.FC<SubmissionPackagerViewProps> = ({
  activeTarget,
  onGenerateBundle,
  isPackaging,
}) => {
  const bundle = activeTarget.submissionBundle;
  const project = activeTarget.project;
  const spec = activeTarget.spec;

  const [copiedPitch, setCopiedPitch] = useState(false);
  const [copiedFull, setCopiedFull] = useState(false);
  const [copiedScript, setCopiedScript] = useState(false);

  const handleCopy = (text: string, setCopiedState: (v: boolean) => void) => {
    navigator.clipboard.writeText(text);
    setCopiedState(true);
    setTimeout(() => setCopiedState(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!bundle) return;
    const mdContent = `# Submission Package: ${activeTarget.title}
Platform: ${activeTarget.platform}
Generated by: AI Bounty Radar Engine
Date: ${new Date().toISOString().split('T')[0]}

---

## 1. 150-Word Elevator Pitch
${bundle.shortPitch}

---

## 2. Key Technical Highlights
${bundle.keyHighlights.map((h) => `- ${h}`).join('\n')}

---

## 3. Comprehensive Project Writeup
${bundle.fullDescription}

---

## 4. 2-Minute Demo Video Script
${bundle.videoScript}

---

## 5. Artifact Links
- Repository: https://github.com/autonomous-competitor/${project?.projectName || 'app'}
- Live Demo: https://${project?.projectName || 'app'}-6n5got2.run.app
- SHA-256 Codebase Fingerprint: ${activeTarget.qaResult?.fingerprint || 'Verified'}
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project?.projectName || 'submission'}-package.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="text-xs text-slate-400">
            <span>Target: <strong className="text-slate-200">{activeTarget.title}</strong></span>
            <span className="mx-2" aria-hidden="true">·</span>
            <span>Platform: {activeTarget.platform}</span>
          </div>
          <h1 className="text-xl font-bold text-white tracking-tight mt-1">
            Automated Submission Packager
          </h1>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={onGenerateBundle}
            disabled={isPackaging}
            className="px-3.5 py-1.5 text-xs font-medium text-slate-200 bg-slate-900 border border-slate-700 hover:bg-slate-800 disabled:opacity-50 rounded-md transition-colors inline-flex items-center gap-1.5"
          >
            <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
            <span>{isPackaging ? 'Packaging with Gemini...' : 'Re-Package Submission'}</span>
          </button>

          {bundle && (
            <button
              onClick={handleDownloadMarkdown}
              className="px-4 py-1.5 text-xs font-semibold text-slate-950 bg-cyan-400 hover:bg-cyan-300 rounded-md transition-colors inline-flex items-center gap-1.5 shadow-sm shadow-cyan-900/30"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Submission Bundle (.md)</span>
            </button>
          )}
        </div>
      </div>

      {bundle ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Column: Short Pitch & Highlights (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            {/* 150-Word Elevator Pitch */}
            <div className="p-4 bg-slate-900 border border-slate-800 rounded-lg space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-200 flex items-center gap-1.5">
                  <FileText className="w-4 h-4 text-cyan-400" />
                  <span>150-Word Elevator Pitch</span>
                </span>
                <button
                  onClick={() => handleCopy(bundle.shortPitch, setCopiedPitch)}
                  className="px-2 py-0.5 text-[11px] text-slate-400 hover:text-white inline-flex items-center gap-1 transition-colors"
                >
                  {copiedPitch ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copiedPitch ? 'Copied' : 'Copy'}</span>
                </button>
              </div>

              <div className="p-3 bg-slate-950/80 border border-slate-800/80 rounded text-xs text-slate-300 leading-relaxed select-text">
                {bundle.shortPitch}
              </div>
            </div>

            {/* Key Technical Highlights */}
            <div className="p-4 bg-slate-900 border border-slate-800 rounded-lg space-y-3">
              <span className="text-xs font-semibold text-slate-200">
                Key Technical Highlights
              </span>
              <ul className="space-y-2 text-xs">
                {bundle.keyHighlights.map((hl, i) => (
                  <li key={i} className="p-2.5 bg-slate-950/60 border border-slate-800/80 rounded text-slate-300 flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 mt-1.5 shrink-0" />
                    <span>{hl}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Ready Submission Artifacts */}
            <div className="p-4 bg-slate-900/60 border border-slate-800 rounded-lg space-y-2.5 text-xs">
              <div className="font-semibold text-slate-300">Deliverable Links</div>
              <div className="flex justify-between items-center p-2 bg-slate-950/80 border border-slate-800/80 rounded text-slate-300">
                <span>GitHub Repository:</span>
                <span className="font-mono text-cyan-300 text-[11px]">github.com/auto-competitor/{project?.projectName || 'repo'}</span>
              </div>
              <div className="flex justify-between items-center p-2 bg-slate-950/80 border border-slate-800/80 rounded text-slate-300">
                <span>Live Deployment:</span>
                <span className="font-mono text-cyan-300 text-[11px]">https://{project?.projectName || 'demo'}-6n5got2.run.app</span>
              </div>
            </div>
          </div>

          {/* Right Column: Full Writeup & Video Script (7 cols) */}
          <div className="lg:col-span-7 space-y-6">
            {/* Full 800-Word Comprehensive Writeup */}
            <div className="p-4 bg-slate-900 border border-slate-800 rounded-lg space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-200 flex items-center gap-1.5">
                  <FileText className="w-4 h-4 text-cyan-400" />
                  <span>Comprehensive Project Writeup (Judging Aligned)</span>
                </span>
                <button
                  onClick={() => handleCopy(bundle.fullDescription, setCopiedFull)}
                  className="px-2 py-0.5 text-[11px] text-slate-400 hover:text-white inline-flex items-center gap-1 transition-colors"
                >
                  {copiedFull ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copiedFull ? 'Copied' : 'Copy'}</span>
                </button>
              </div>

              <div className="p-4 bg-slate-950/90 border border-slate-800/80 rounded text-xs text-slate-300 leading-relaxed max-h-[340px] overflow-y-auto whitespace-pre-wrap select-text font-mono">
                {bundle.fullDescription}
              </div>
            </div>

            {/* 2-Minute Shot-by-Shot Video Script */}
            <div className="p-4 bg-slate-900 border border-slate-800 rounded-lg space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-200 flex items-center gap-1.5">
                  <Video className="w-4 h-4 text-cyan-400" />
                  <span>2-Minute Walkthrough Video Script</span>
                </span>
                <button
                  onClick={() => handleCopy(bundle.videoScript, setCopiedScript)}
                  className="px-2 py-0.5 text-[11px] text-slate-400 hover:text-white inline-flex items-center gap-1 transition-colors"
                >
                  {copiedScript ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copiedScript ? 'Copied' : 'Copy'}</span>
                </button>
              </div>

              <div className="p-4 bg-slate-950/90 border border-slate-800/80 rounded text-xs text-slate-300 leading-relaxed max-h-[220px] overflow-y-auto whitespace-pre-wrap select-text font-mono">
                {bundle.videoScript}
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="p-12 text-center text-slate-400 text-xs border border-slate-800 rounded-lg bg-slate-900/40 space-y-3">
          <p>Submission package has not been assembled yet for this competition.</p>
          <button
            onClick={onGenerateBundle}
            disabled={isPackaging}
            className="px-4 py-2 text-xs font-semibold text-slate-950 bg-cyan-400 hover:bg-cyan-300 rounded-md transition-colors"
          >
            {isPackaging ? 'Synthesizing with Gemini 3.8...' : 'Generate Complete Submission Package'}
          </button>
        </div>
      )}
    </div>
  );
};
